language: php

php:
  - 5.6

sudo: false

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon

before_install:
  - travis_retry composer self-update
  - composer install --prefer-dist --no-interaction
  - mysql -e "create database IF NOT EXISTS orchestra;" -uroot
  - gunzip < tests/assets/orchestra.sql.gz | mysql orchestra -uroot
  - vendor/bin/install-phalcon.sh

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
